version: '3.8'

services:
  frontend:
    image: node:14
    container_name: frontend
    restart: always
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile  # Adjust the path as needed
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass

volumes:
  mongodb_data:
    driver: local
